package com.weeklyroster.service;

import com.weeklyroster.config.RailwayEnvironmentPostProcessor;
import com.weeklyroster.entity.Employee;
import com.weeklyroster.entity.Role;
import com.weeklyroster.entity.User;
import com.weeklyroster.repository.EmployeeRepository;
import com.weeklyroster.repository.UserRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.StandardEnvironment;
import org.springframework.mock.env.MockEnvironment;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import javax.sql.DataSource;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("local")
@TestPropertySource(properties = {"wrms.dev.credential-mirror.enabled=false"})
public class Batch73DualDatabaseSupportTest {

    @Autowired
    private DataSource dataSource;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private EmployeeRepository employeeRepository;

    @Test
    @DisplayName("SQLite Local Mode: Verifies SQLite driver, dialect, and data/wrms.db file existence")
    void testSqliteLocalStartupAndDatabaseFileCreation() throws Exception {
        assertNotNull(dataSource, "DataSource must be injected");

        try (Connection connection = dataSource.getConnection()) {
            assertNotNull(connection, "Connection must be established");
            DatabaseMetaData metaData = connection.getMetaData();
            String productName = metaData.getDatabaseProductName();
            assertNotNull(productName);
            assertTrue(productName.toLowerCase().contains("sqlite"),
                    "Database product must be SQLite in local profile, but was: " + productName);
        }

        File dbFile = new File("data/wrms.db");
        assertTrue(dbFile.exists(), "SQLite database file 'data/wrms.db' must exist on disk");
        assertTrue(dbFile.length() > 0, "SQLite database file must not be empty");
    }

    @Test
    @DisplayName("Seed Data in SQLite: Admin user and default employee workforce seeded automatically")
    void testDefaultAdminAndEmployeesSeededInSqlite() {
        Optional<User> admin = userRepository.findByUsername("Admin");
        assertTrue(admin.isPresent(), "Default Admin user must be present in SQLite");
        assertEquals(Role.ROLE_ADMIN, admin.get().getRole());

        List<Employee> employees = employeeRepository.findAll();
        assertFalse(employees.isEmpty(), "Default employees must be present in SQLite");
        assertTrue(employeeRepository.existsByEmployeeCode("EMP001"), "EMP001 must exist in SQLite");
    }

    @Test
    @DisplayName("Data Persistence in SQLite: Entity CRUD survives in local SQLite database")
    void testSqliteDataPersistence() {
        String testCode = "B73LOCAL" + (System.currentTimeMillis() % 10000);
        Employee emp = new Employee();
        emp.setEmployeeCode(testCode);
        emp.setFirstName("SQLite");
        emp.setLastName("Tester");
        emp.setEmail("sqlite." + testCode + "@example.com");
        emp.setActive(true);
        emp.setGender(com.weeklyroster.entity.Gender.MALE);

        Employee saved = employeeRepository.save(emp);
        assertNotNull(saved.getId(), "Employee ID must be generated by SQLite");

        Optional<Employee> fetched = employeeRepository.findByEmployeeCode(testCode);
        assertTrue(fetched.isPresent(), "Saved employee must be retrievable from SQLite");
        assertEquals("SQLite", fetched.get().getFirstName());
    }

    @Test
    @DisplayName("Configuration Files: application-local and application-prod properties exist and are valid")
    void testConfigFilesExist() {
        Path localProps = Path.of("src/main/resources/application-local.properties");
        Path prodProps = Path.of("src/main/resources/application-prod.properties");
        Path appProps = Path.of("src/main/resources/application.properties");

        assertTrue(Files.exists(localProps), "application-local.properties must exist");
        assertTrue(Files.exists(prodProps), "application-prod.properties must exist");
        assertTrue(Files.exists(appProps), "application.properties must exist");

        assertDoesNotThrow(() -> {
            String localContent = Files.readString(localProps);
            assertTrue(localContent.contains("jdbc:sqlite:data/wrms.db"), "local profile must configure SQLite url");
            assertTrue(localContent.contains("org.sqlite.JDBC"), "local profile must configure SQLite driver");
            assertTrue(localContent.contains("SQLiteDialect"), "local profile must configure SQLite dialect");

            String prodContent = Files.readString(prodProps);
            assertTrue(prodContent.contains("jdbc:mysql:"), "prod profile must configure MySQL url");
            assertTrue(prodContent.contains("com.mysql.cj.jdbc.Driver"), "prod profile must configure MySQL driver");
            assertTrue(prodContent.contains("MySQLDialect"), "prod profile must configure MySQL dialect");

            String appContent = Files.readString(appProps);
            assertTrue(appContent.contains("spring.profiles.default=local"), "application.properties must default to local");
        });
    }

    @Test
    @DisplayName("RailwayEnvironmentPostProcessor: Correctly detects local vs Railway production environments")
    void testRailwayEnvironmentPostProcessorLogic() {
        RailwayEnvironmentPostProcessor processor = new RailwayEnvironmentPostProcessor();

        // 1. Local environment (no remote host)
        MockEnvironment localEnv = new MockEnvironment();
        processor.postProcessEnvironment(localEnv, null);
        assertEquals("local", localEnv.getActiveProfiles()[0], "Local environment must activate 'local' profile");
        assertEquals("jdbc:sqlite:data/wrms.db", localEnv.getProperty("spring.datasource.url"));
        assertEquals("org.sqlite.JDBC", localEnv.getProperty("spring.datasource.driver-class-name"));
        assertEquals("org.hibernate.community.dialect.SQLiteDialect", localEnv.getProperty("spring.jpa.database-platform"));

        // 2. Remote Railway environment with MYSQLHOST
        MockEnvironment railwayEnv = new MockEnvironment();
        railwayEnv.setProperty("MYSQLHOST", "containers-us-west-1.railway.app");
        railwayEnv.setProperty("MYSQLPORT", "6543");
        railwayEnv.setProperty("MYSQLDATABASE", "railway");
        railwayEnv.setProperty("MYSQLUSER", "root");
        railwayEnv.setProperty("MYSQLPASSWORD", "secret123");
        processor.postProcessEnvironment(railwayEnv, null);

        assertEquals("prod", railwayEnv.getActiveProfiles()[0], "Railway environment must activate 'prod' profile");
        assertTrue(railwayEnv.getProperty("spring.datasource.url").contains("jdbc:mysql://containers-us-west-1.railway.app:6543/railway"));
        assertEquals("org.hibernate.dialect.MySQLDialect", railwayEnv.getProperty("spring.jpa.database-platform"));
    }
}
