package com.weeklyroster.service;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

public class StaticResourceTest {

    @Test
    @DisplayName("GET /favicon.ico -> Static resource exists on classpath with valid ICO header")
    void testFaviconResource_ExistsAndValid() throws Exception {
        ClassPathResource faviconResource = new ClassPathResource("static/favicon.ico");
        assertTrue(faviconResource.exists(), "static/favicon.ico must exist on classpath");
        assertTrue(faviconResource.contentLength() > 0, "favicon.ico must not be empty");

        try (InputStream is = faviconResource.getInputStream()) {
            byte[] header = is.readNBytes(6);
            assertEquals(6, header.length);
            // Valid ICO signature: reserved=0, type=1 (icon), imageCount=1
            assertEquals(0, header[0]);
            assertEquals(0, header[1]);
            assertEquals(1, header[2]);
            assertEquals(0, header[3]);
            assertEquals(1, header[4]);
            assertEquals(0, header[5]);
        }
    }

    @Test
    @DisplayName("index.html contains proper favicon link declaration")
    void testIndexHtml_ContainsFaviconLink() throws Exception {
        ClassPathResource indexResource = new ClassPathResource("static/index.html");
        assertTrue(indexResource.exists(), "static/index.html must exist on classpath");

        String content;
        try (InputStream is = indexResource.getInputStream()) {
            content = new String(is.readAllBytes(), StandardCharsets.UTF_8);
        }

        assertTrue(content.contains("<link rel=\"icon\" type=\"image/x-icon\" href=\"/favicon.ico\">"),
                "index.html must include <link rel=\"icon\" type=\"image/x-icon\" href=\"/favicon.ico\">");
    }

    @Test
    @DisplayName("All core static web assets are present on classpath")
    void testCoreStaticWebAssets_Exist() {
        assertTrue(new ClassPathResource("static/index.html").exists());
        assertTrue(new ClassPathResource("static/styles.css").exists());
        assertTrue(new ClassPathResource("static/app.js").exists());
        assertTrue(new ClassPathResource("static/favicon.ico").exists());
    }

    @Test
    @DisplayName("GET /favicon.ico via ResourceHttpRequestHandler returns HTTP 200 and image bytes")
    void testFaviconHttpRequest_Returns200() throws Exception {
        org.springframework.web.servlet.resource.ResourceHttpRequestHandler handler = new org.springframework.web.servlet.resource.ResourceHttpRequestHandler();
        handler.setLocations(java.util.List.of(new ClassPathResource("static/")));
        handler.afterPropertiesSet();

        org.springframework.mock.web.MockHttpServletRequest request = new org.springframework.mock.web.MockHttpServletRequest("GET", "/favicon.ico");
        request.setAttribute(org.springframework.web.servlet.HandlerMapping.PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE, "favicon.ico");
        org.springframework.mock.web.MockHttpServletResponse response = new org.springframework.mock.web.MockHttpServletResponse();

        handler.handleRequest(request, response);

        assertEquals(200, response.getStatus(), "GET /favicon.ico must return HTTP 200");
        assertTrue(response.getContentAsByteArray().length > 0, "Favicon response body must not be empty");
        assertEquals(572, response.getContentAsByteArray().length, "Favicon should match generated byte length (572 bytes)");
    }
}
