package com.weeklyroster.entity;

public enum AuditAction {
    ROSTER_GENERATED,
    ROSTER_REGENERATED,
    ROSTER_PUBLISHED,
    ROSTER_LOCKED,
    ROSTER_UNLOCKED,
    ROSTER_DELETED,
    ASSIGNMENT_CREATED,
    ASSIGNMENT_MODIFIED,
    ASSIGNMENT_DELETED,
    SHIFT_OVERRIDDEN,
    SHIFT_SWAPPED,
    LEAVE_APPLIED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_MODIFIED,
    LEAVE_CANCELLED,
    EMAIL_SENT,
    NOTIFICATION_SENT,
    AUTOMATIC_GENERATION,
    PROFILE_CHANGE_REQUESTED,
    PROFILE_CHANGE_APPROVED,
    PROFILE_CHANGE_REJECTED
}
