package com.weeklyroster.entity;

public enum LeaveStatus {
    PENDING,
    APPROVED,
    REJECTED,
    PENDING_MODIFICATION,
    MODIFICATION_APPROVED,
    MODIFICATION_REJECTED,
    PENDING_CANCELLATION,
    CANCELLATION_APPROVED,
    CANCELLATION_REJECTED,
    CANCELLED
}
